# Generated by Django 4.2.27 on 2025-12-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate_8h', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_9h', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_12h', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_subrented', models.BooleanField(default=False)),
                ('owner_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
