# Generated by Django 4.2.27 on 2025-12-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cranes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crane',
            name='rate_12h',
        ),
        migrations.RemoveField(
            model_name='crane',
            name='rate_8h',
        ),
        migrations.RemoveField(
            model_name='crane',
            name='rate_9h',
        ),
    ]
