# Generated by Django 4.2.27 on 2025-12-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('drivers', '0001_initial'),
        ('cranes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shift_type', models.CharField(choices=[('8h', '8 Hours'), ('9h', '9 Hours'), ('12h', '12 Hours')], default='8h', max_length=3)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('driver_wage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='clients.client')),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='cranes.crane')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Time Sheet',
                'verbose_name_plural': 'Time Sheets',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
