# Generated by Django 4.2.27 on 2025-12-06 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('drivers', '0001_initial'),
        ('cranes', '0001_initial'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Location/Site')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_operating_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_attendance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_driver_wage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supervisor_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_sheets', to='clients.client', verbose_name='Project/Customer')),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_sheets', to='cranes.crane', verbose_name='Machine/Equipment')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_sheets', to='drivers.driver', verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Monthly Time Sheet',
                'verbose_name_plural': 'Monthly Time Sheets',
                'ordering': ['-year', '-month'],
                'unique_together': {('client', 'crane', 'driver', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=20)),
                ('weekday_ar', models.CharField(blank=True, max_length=20)),
                ('from_time', models.TimeField(blank=True, null=True, verbose_name='From (من)')),
                ('to_time', models.TimeField(blank=True, null=True, verbose_name='To (إلى)')),
                ('operating_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Operating Hours (إجمالي ساعات التشغيل)')),
                ('trips', models.PositiveIntegerField(default=0, verbose_name='Trips (رحلات)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes (البيان)')),
                ('attendance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Attendance Hours (إجمالي ساعات الحضور)')),
                ('monthly_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='timesheets.monthlytimesheet')),
            ],
            options={
                'verbose_name': 'Daily Entry',
                'verbose_name_plural': 'Daily Entries',
                'ordering': ['monthly_sheet', 'day_number'],
                'unique_together': {('monthly_sheet', 'day_number')},
            },
        ),
    ]
