# Generated by Django 4.2.27 on 2025-12-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_monthlytimesheet_dailyentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='to_time',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='from_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='From (من)'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='to_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='To (إلى)'),
        ),
    ]
