# Generated by Django 4.2.27 on 2025-12-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_alter_dailyentry_from_time_alter_dailyentry_to_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='from_period',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2, verbose_name='AM/PM'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='to_period',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='PM', max_length=2, verbose_name='AM/PM'),
        ),
    ]
