# Generated by Django 4.2.27 on 2025-12-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_dailyentry_from_period_dailyentry_to_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hourly Rate (سعر الساعة)'),
        ),
        migrations.AddField(
            model_name='monthlytimesheet',
            name='default_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hourly Rate'),
        ),
    ]
