# Generated by Django 4.2.27 on 2025-12-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_dailyentry_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='daily_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Daily Total (إجمالي اليوم)'),
        ),
        migrations.AddField(
            model_name='monthlytimesheet',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytimesheet',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='from_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='From (من)'),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='hourly_rate',
            field=models.PositiveIntegerField(default=0, verbose_name='Hourly Rate (سعر الساعة)'),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='to_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='To (إلى)'),
        ),
        migrations.AlterField(
            model_name='monthlytimesheet',
            name='default_hourly_rate',
            field=models.PositiveIntegerField(default=0, verbose_name='Hourly Rate'),
        ),
        migrations.AlterField(
            model_name='monthlytimesheet',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlytimesheet',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
