# Generated by Django 4.2.27 on 2025-12-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_dailyentry_daily_total_monthlytimesheet_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytimesheet',
            name='shift_divisor',
            field=models.PositiveIntegerField(default=8, verbose_name='Shift Divisor (hours per shift)'),
        ),
        migrations.AddField(
            model_name='monthlytimesheet',
            name='total_shift_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Total Shift Days'),
        ),
    ]
