# Generated by Django 4.2.27 on 2025-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_add_shift_divisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytimesheet',
            name='default_hourly_rate',
        ),
        migrations.AddField(
            model_name='monthlytimesheet',
            name='price_per_day',
            field=models.PositiveIntegerField(default=0, verbose_name='Price per Day (سعر اليوم)'),
        ),
    ]
