# Generated by Django 4.2.27 on 2025-12-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_loan'),
        ('timesheets', '0008_rename_hourly_rate_to_price_per_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries', to='drivers.driver', verbose_name='Driver'),
        ),
        migrations.AddField(
            model_name='monthlytimesheet',
            name='driver_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Drivers'),
        ),
    ]
