# Generated by Django 4.2.27 on 2025-12-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch')], max_length=20)),
                ('status', models.CharField(choices=[('TO_PREPARE', 'To Prepare'), ('READY', 'Ready')], default='TO_PREPARE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='drivers.driver')),
            ],
            options={
                'ordering': ['-date', 'driver__name'],
            },
        ),
    ]
