# Generated by Django 4.2.27 on 2025-12-07 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_loan'),
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='meal',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'فطار'), ('LUNCH', 'غداء')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.CharField(choices=[('TO_PREPARE', 'للتحضير'), ('READY', 'جاهز')], default='TO_PREPARE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('driver', 'date', 'meal_type')},
        ),
    ]
